# Generated by Django 3.1.1 on 2020-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0002_auto_20200928_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_of_file',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_recived',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_responded',
            field=models.DateTimeField(),
        ),
    ]
