# Generated by Django 3.1.1 on 2020-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0003_auto_20200928_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_of_file',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_recived',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_responded',
            field=models.DateField(),
        ),
    ]
