# Generated by Django 3.1.1 on 2020-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0004_auto_20200928_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='files',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
